language: ruby
rvm:
  - "2.0.0"

notifications:
  email:
    - justin@curationexperts.com

script:
  - bundle exec rake db:reset
  - bundle exec rake

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/redis.yml.sample config/redis.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/initializers/secret_token.rb.sample config/initializers/secret_token.rb

services:
  - redis-server
